// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ResidencySelectorController from "./residency_selector_controller"
application.register("residency-selector", ResidencySelectorController)

import GeographicCoverAreasController from "./geographic_cover_areas_controller"
application.register("geographic-cover-areas", GeographicCoverAreasController)

import BenefitLimitRulesController from "./benefit_limit_rules_controller"
application.register("benefit-limit-rules", BenefitLimitRulesController)
